# Generated by Django 5.0.2 on 2024-02-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=30)),
                ('authorname', models.CharField(max_length=20)),
                ('bookprize', models.IntegerField()),
                ('contemail', models.EmailField(max_length=254)),
            ],
        ),
    ]
